project_id = "datdwxsugeobqigtopnz"

[functions.strava-auth]
verify_jwt = false

[functions.strava-import]
verify_jwt = false

[functions.intervals-sync]
verify_jwt = false

[functions.google-fit-auth]
verify_jwt = false

[functions.google-fit-callback]
verify_jwt = false

[functions.google-fit-sleep]
verify_jwt = false
