import MarketingPageLayout from "@/components/MarketingPageLayout";

const Privacy = () => {
  const today = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });

  return (
    <MarketingPageLayout
      title="Privacy Policy | Scarpers AI Running Coach"
      description="How Scarpers collects, uses and protects your data — including activity, sleep and onboarding information used to generate AI training plans."
      canonicalPath="/privacy"
    >
    <div className="space-y-6 pb-12">
      <h1 className="text-2xl font-bold">Privacy Policy</h1>
      <p className="text-sm text-muted-foreground">Last updated: {today}</p>

      <section className="space-y-2 rounded-xl border border-destructive/30 bg-destructive/5 p-4">
        <h2 className="text-lg font-semibold text-destructive">Important Disclaimer</h2>
        <p className="text-sm leading-relaxed">
          Scarpers is an AI-powered training plan tool and is not a replacement for a qualified running coach,
          physiotherapist, or medical professional. By using this service you acknowledge that you do so entirely at
          your own risk. Scarpers accepts no liability for any injury, illness, or adverse health outcome arising from
          the use of training plans generated on this platform. Always consult a qualified professional before
          beginning any new exercise programme, particularly if you have a pre-existing medical condition or injury
          history.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">1. Who We Are</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Scarpers operates the website scarpers.co.uk — an AI-powered running plan platform that generates
          personalised training plans for users working towards running goals such as completing a 5K. For questions
          about this policy contact:{" "}
          <a className="text-primary underline" href="mailto:hello@scarpers.co.uk">hello@scarpers.co.uk</a>.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">2. What Data We Collect</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">We collect the following information when you use Scarpers:</p>
        <ul className="list-disc pl-5 text-sm text-muted-foreground space-y-1">
          <li>Name and email address when you register</li>
          <li>Fitness information you provide including age, weight, injury history, HR zones, and race goals</li>
          <li>Training activity data if you connect a Garmin device</li>
          <li>Usage data including pages visited and features used</li>
          <li>Device and browser information</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">3. How We Use Your Data</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">We use your data to:</p>
        <ul className="list-disc pl-5 text-sm text-muted-foreground space-y-1">
          <li>Generate personalised training plans tailored to your profile</li>
          <li>Sync workouts to your connected Garmin device</li>
          <li>Improve the platform and AI plan generation</li>
          <li>Send you training reminders and plan updates if you opt in</li>
          <li>Comply with legal obligations</li>
        </ul>
        <p className="text-sm text-muted-foreground leading-relaxed">
          We do not sell your personal data to third parties under any circumstances.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">4. AI-Generated Plans</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Training plans on Scarpers are generated by artificial intelligence. While we use best efforts to ensure
          plans are appropriate and safe, AI-generated content may not account for every individual circumstance. You
          are responsible for assessing whether any plan is suitable for your personal health and fitness level.
          Scarpers is not liable for any harm resulting from following an AI-generated training plan.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">5. Third Party Services</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          We use the following third party services which may process your data:
        </p>
        <ul className="list-disc pl-5 text-sm text-muted-foreground space-y-1">
          <li>Anthropic — AI plan generation</li>
          <li>Garmin — workout sync and activity data (if connected)</li>
          <li>Google — analytics and site verification</li>
          <li>Lovable — platform infrastructure</li>
        </ul>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Each of these services operates under their own privacy policy.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">6. Data Storage and Security</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Your data is stored securely. We use industry-standard encryption and access controls to protect your
          information. We retain your data for as long as your account is active. You may request deletion of your
          data at any time by contacting{" "}
          <a className="text-primary underline" href="mailto:hello@scarpers.co.uk">hello@scarpers.co.uk</a>.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">7. Your Rights</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">Under UK GDPR you have the right to:</p>
        <ul className="list-disc pl-5 text-sm text-muted-foreground space-y-1">
          <li>Access the personal data we hold about you</li>
          <li>Request correction of inaccurate data</li>
          <li>Request deletion of your data</li>
          <li>Object to processing of your data</li>
          <li>Request a copy of your data in a portable format</li>
        </ul>
        <p className="text-sm text-muted-foreground leading-relaxed">
          To exercise any of these rights contact{" "}
          <a className="text-primary underline" href="mailto:hello@scarpers.co.uk">hello@scarpers.co.uk</a>.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">8. Cookies</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Scarpers uses essential cookies to keep you logged in and remember your preferences. We may use analytics
          cookies to understand how the platform is used. You can manage cookie preferences in your browser settings.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">9. Children</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Scarpers is not intended for users under the age of 16. We do not knowingly collect data from children.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">10. Changes to This Policy</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          We may update this policy from time to time. We will notify registered users of any significant changes by
          email. Continued use of the platform after changes constitutes acceptance of the updated policy.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">11. Contact</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          For any privacy related questions or requests:
          <br />
          Email: <a className="text-primary underline" href="mailto:hello@scarpers.co.uk">hello@scarpers.co.uk</a>
          <br />
          Website: <a className="text-primary underline" href="https://www.scarpers.co.uk/">www.scarpers.co.uk</a>
        </p>
      </section>
    </div>
    </MarketingPageLayout>
  );
};

export default Privacy;
