import MarketingPageLayout from "@/components/MarketingPageLayout";

const Terms = () => {
  const today = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });

  return (
    <MarketingPageLayout
      title="Terms of Service | Scarpers AI Running Coach"
      description="The terms governing your use of Scarpers — the AI running coach that generates free personalised training plans."
      canonicalPath="/terms"
    >
      <article className="prose prose-invert max-w-none">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2" style={{ fontFamily: "'Bebas Neue', sans-serif" }}>
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground">Last updated: {today}</p>

        <h2 className="text-xl font-semibold mt-8 mb-2">1. Acceptance</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          By creating an account or using Scarpers (scarpers.co.uk) you agree to these terms. If you do not
          agree, please do not use the service.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">2. The Service</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          Scarpers is an AI-powered running coach that generates personalised training plans, analyses your
          activity and sleep data, and provides daily readiness and post-run feedback. The service is offered
          free of charge and is provided "as is" without warranty of any kind.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">3. Health &amp; Safety Disclaimer</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          Scarpers is not a substitute for a qualified running coach, physiotherapist or medical professional.
          Training plans are generated by AI and may not account for every individual circumstance. You use
          Scarpers entirely at your own risk. Always consult a qualified professional before starting a new
          exercise programme, particularly if you have a pre-existing condition, injury, are pregnant, or are
          returning from surgery. Scarpers accepts no liability for any injury, illness or adverse outcome
          arising from use of the service.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">4. Your Account</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          You are responsible for keeping your login credentials secure and for all activity under your account.
          You must provide accurate onboarding information — inaccurate fitness, injury or health information
          can result in unsuitable plans.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">5. Acceptable Use</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          You agree not to misuse the service, attempt to access other users' data, scrape the platform, abuse
          the AI, or use Scarpers for any unlawful purpose.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">6. Intellectual Property</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          The Scarpers name, logo, blog content and software are owned by Scarpers. Plans generated for you are
          yours to use personally. Please don't republish blog posts or AI-generated coaching content as your
          own.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">7. Third-Party Services</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          Scarpers integrates with Strava, Intervals.icu, Google Fit, Health Connect and others. Your use of
          those services is governed by their own terms.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">8. Termination</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          You may delete your account at any time from Settings. We may suspend or terminate accounts that
          breach these terms.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">9. Changes</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          We may update these terms. Significant changes will be communicated by email to registered users.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">10. Contact</h2>
        <p className="text-muted-foreground leading-relaxed text-sm">
          Questions: <a className="text-primary underline" href="mailto:hello@scarpers.co.uk">hello@scarpers.co.uk</a>
        </p>
      </article>
    </MarketingPageLayout>
  );
};

export default Terms;
