// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-activities.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_activities_default = defineTool({
  name: "list_activities",
  title: "List recent activities",
  description: "List the signed-in user's recent Scarpers activities (runs, rides, etc.), newest first. Returns id, start_time, activity_type, distance in km, duration in minutes, and average heart rate.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max activities to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("activities").select("id,start_time,activity_type,distance_meters,duration_seconds,avg_heart_rate").order("start_time", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((a) => ({
      id: a.id,
      start_time: a.start_time,
      type: a.activity_type,
      distance_km: a.distance_meters ? +(a.distance_meters / 1e3).toFixed(2) : null,
      duration_min: a.duration_seconds ? +(a.duration_seconds / 60).toFixed(1) : null,
      avg_hr: a.avg_heart_rate
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { activities: rows }
    };
  }
});

// src/lib/mcp/tools/get-activity.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_activity_default = defineTool2({
  name: "get_activity",
  title: "Get activity detail",
  description: "Fetch full detail for a single activity by id (must belong to the signed-in user).",
  inputSchema: { id: z2.string().uuid().describe("Activity UUID from list_activities.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("activities").select(
      "id,start_time,activity_type,distance_meters,duration_seconds,avg_heart_rate,max_heart_rate,avg_speed,max_speed,avg_cadence,calories,training_load,training_effect,total_ascent,total_descent"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { activity: data }
    };
  }
});

// src/lib/mcp/tools/get-current-plan.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_current_plan_default = defineTool3({
  name: "get_current_training_plan",
  title: "Get current training plan",
  description: "Return the signed-in user's current (non-archived) Scarpers training plan, including race distance, race date, start date, and the full markdown plan content.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("training_plans").select("id,race_distance,race_date,start_date,goal_time,training_days,paused_until,content,created_at").eq("archived", false).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No active training plan." }] };
    return {
      content: [{ type: "text", text: data.content }],
      structuredContent: { plan: data }
    };
  }
});

// src/lib/mcp/tools/list-sleep.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_sleep_default = defineTool4({
  name: "list_sleep",
  title: "List recent sleep",
  description: "Return the signed-in user's daily sleep summaries (duration, deep/light/REM minutes, sleep score, HRV, resting HR) for the last N days.",
  inputSchema: {
    days: z3.number().int().min(1).max(90).optional().describe("Number of past days to include (default 14).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const n = days ?? 14;
    const since = new Date(Date.now() - n * 864e5).toISOString().slice(0, 10);
    const { data, error } = await sb4(ctx).from("daily_metrics").select(
      "date,sleep_duration_seconds,sleep_score,deep_sleep_minutes,light_sleep_minutes,rem_sleep_minutes,awake_during_night_minutes,hrv,resting_heart_rate"
    ).gte("date", since).order("date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sleep: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-readiness.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_readiness_default = defineTool5({
  name: "get_readiness_today",
  title: "Get today's readiness",
  description: "Return the signed-in user's most recent Scarpers readiness snapshot: score, contributing factors, coach insight and recommendation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("readiness_snapshots").select("recorded_at,score,kind,factors,insight,advice,recommendation").order("recorded_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No readiness snapshot yet." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { readiness: data }
    };
  }
});

// src/lib/mcp/tools/log-nutrition.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_nutrition_default = defineTool6({
  name: "log_nutrition",
  title: "Log a nutrition entry",
  description: "Add a food entry to the signed-in user's Scarpers nutrition diary. Values are for the actual portion consumed (not per 100g).",
  inputSchema: {
    food_name: z4.string().min(1),
    meal_type: z4.enum(["breakfast", "lunch", "dinner", "snack"]),
    quantity_g: z4.number().positive(),
    calories: z4.number().min(0),
    carbs_g: z4.number().min(0).optional(),
    protein_g: z4.number().min(0).optional(),
    fat_g: z4.number().min(0).optional(),
    sat_fats_g: z4.number().min(0).optional(),
    salt_mg: z4.number().min(0).optional(),
    alcohol_units: z4.number().min(0).optional(),
    brand: z4.string().optional(),
    log_date: z4.string().optional().describe("YYYY-MM-DD; defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb6(ctx).from("nutrition_logs").insert({
      user_id: ctx.getUserId(),
      food_name: input.food_name,
      meal_type: input.meal_type,
      quantity_g: input.quantity_g,
      calories: input.calories,
      carbs_g: input.carbs_g ?? 0,
      protein_g: input.protein_g ?? 0,
      fat_g: input.fat_g ?? 0,
      sat_fats_g: input.sat_fats_g ?? 0,
      salt_mg: input.salt_mg ?? 0,
      alcohol_units: input.alcohol_units ?? 0,
      brand: input.brand ?? null,
      log_date: input.log_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      source: "mcp"
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${input.food_name} (${input.calories} kcal).` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "datdwxsugeobqigtopnz";
var mcp_default = defineMcp({
  name: "scarpers-mcp",
  title: "Scarpers",
  version: "0.1.0",
  instructions: "Scarpers running coach tools. Read the signed-in user's recent activities, sleep, readiness and current training plan, and log nutrition entries on their behalf. All tools act as the signed-in Scarpers user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_activities_default, get_activity_default, get_current_plan_default, list_sleep_default, get_readiness_default, log_nutrition_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
