ALTER TABLE public.training_plans
  ADD COLUMN IF NOT EXISTS paused_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS paused_until TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS pause_reason TEXT NULL,
  ADD COLUMN IF NOT EXISTS race_date_mode TEXT NULL;